'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VendorContractInfo

    '''<summary>
    '''rcboDefaultWC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcboDefaultWC As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ods_WCCertTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_WCCertTypes As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''rcboPerItemContract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcboPerItemContract As Global.Telerik.Web.UI.RadComboBox
End Class
