'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VendorNameAddress

    '''<summary>
    '''rtbVendorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbVendorName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rfvName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rtbVendorAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbVendorAddress1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rfvAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAddress1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rtbVendorAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbVendorAddress2 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtbVendorCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbVendorCity As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rfvCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rcboVendorState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcboVendorState As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''odsStateAbbrevList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsStateAbbrevList As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''rtbVendorZIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbVendorZIP As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rfvZIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvZIP As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rmtbVendorPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rmtbVendorPhone As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''rmtbVendorFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rmtbVendorFax As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''rtbVendorEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtbVendorEmail As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''vsValidations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsValidations As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''rbtnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnNext As Global.Telerik.Web.UI.RadButton
End Class
